; Mercurial Player - NSIS installer SimpChinese language file

LangString welcomeText ${LANG_SIMPCHINESE} "此程序将引导你完成 ${PRODUCTNAME} 的安装。$\r$\n$\r$\n${PRODUCTNAME} 是一款采用 Material Design 3（MD3）设计风格的本地音乐播放器。$\r$\n$\r$\n点击 [下一步(N)] 继续。"
LangString finishTitle ${LANG_SIMPCHINESE} "安装完成"
LangString finishSubtitle ${LANG_SIMPCHINESE} "安装程序已结束"
LangString finishDescription ${LANG_SIMPCHINESE} "请选择安装完成后的选项："
LangString createDesktopCheckbox ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString createStartMenuCheckbox ${LANG_SIMPCHINESE} "创建开始菜单快捷方式"
LangString launchAppCheckbox ${LANG_SIMPCHINESE} "启动 ${PRODUCTNAME}"
LangString addOrReinstall ${LANG_SIMPCHINESE} "重新安装/修复"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "你的系统中已安装 ${PRODUCTNAME} ${VERSION}。请选择要执行的操作，然后点击 [下一步(N)] 继续。"
LangString appRunning ${LANG_SIMPCHINESE} "${PRODUCTNAME} 正在运行，请先关闭它再重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "${PRODUCTNAME} 正在运行。$\n点击“确定”将自动结束该进程。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择安装 ${PRODUCTNAME} 的方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载，直接安装"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "不卸载（此安装程序不支持在未卸载旧版本的情况下降级）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法结束 ${PRODUCTNAME} 的进程，请手动关闭后重试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "你的系统中已安装更新版本的 ${PRODUCTNAME}。通常不建议安装旧版本；如果你确实需要，建议先卸载当前版本。请选择要执行的操作，然后点击 [下一步(N)] 继续。"
LangString older ${LANG_SIMPCHINESE} "旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "你的系统中已安装$R4版本的 ${PRODUCTNAME}。建议先卸载当前版本再进行安装。请选择要执行的操作，然后点击 [下一步(N)] 继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "此安装程序已禁用降级，无法执行静默安装，请改用图形界面安装程序。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "先卸载，再安装"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "安装 WebView2 失败！本应用依赖 WebView2 才能运行，请重启安装程序后重试。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：下载 WebView2 失败 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 引导程序下载成功"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 引导程序..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：安装 WebView2 失败，退出代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装成功"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除用户数据（配置、音乐库、字体等）"
LangString deleteAppDataNote ${LANG_SIMPCHINESE} "缓存（封面、元数据、WebView 等）始终会被清理。"
